from django.urls import path
from .views import *

urlpatterns=[
    path('indexpage/',index),
    path('customerreg/',regpage),
    path('customerlogin/',customerloginview),
    path('customerprofile/',customerpro),
    path('customeredit/<int:id>',customeredit),
    path('customerfulldisplay/',fullcustomerde),
    path('adminlogin/',adminlogin),
    path('adminprofile/',adminpropage),
    path('productregistration/',productview),
    path('customerprodisplay/',customerprodisplay),
    path('adminproductdisplay',adminprodisplay),
    path('adminprodelete/<int:id>',adminprodelete),
    path('adminproedit/<int:id>',adminproedit),
    path('wishlist/<int:id>',wishlistview),
    path('wishdisplay/',viewwishlist),
    path('singledisplaypage/<int:id>',singledisplay),
    path('logoutpage/',logoutview),
    path('wishdeleteone/<int:id>',wishremoveone),
    path('addtocart/<int:id>',addtocart),
    path('cartdisplay/',newpagecartdesign),
    path('carddelete/<int:id>',cardremoveone),
    path('videoupload/',videoupload),
    path('videocustomerdisp/',videodisp),
    path('adminvideodisplay/',adminvideodisplay),
    path('vidpdfdelete/<int:id>',vidpdfdelete),
    path('videopdfedit/<int:id>',videopdfedit),
    path('productgallerynew/',newgallerypro),
    path('gallerycustomerdisp/',prdgallerycustomerdisp),
    path('galleryadmindisplay/',galleryproadminisplay),
    path('pdtgallerydelete/<int:id>',prdtgallerydelete),
    path('pdtgalleryedit/<int:id>',prdgalleryeditview),
    path('newsfeedview/',newsfeedview),
    path('newsfeeddisplay/',newsfeedcustomerdisp),
    path('newsadmindisplay/',newsadmindisplay),
    path('newsfeeddelete/<int:id>',newsfeeddelete),
    path('newsfeededit/<int:id>',newsfeededit),
    path('newswishlistview/<int:id>',newswishlistview),
    path('viewnewswishlist/',viewnewswishlist),
    path('wishremovenews/<int:id>',wishremovenews),
    path('paymentviewpage/',paymentviewone),
    path('paymentdisplay/',paymentdisplay),
    path('fullpaydisplay/',fullpaydisplaynew),
    path('recommentedview/',recommentedview),
    path('recommenteddisplay/',recommenteddisplay),
    path('recowishdisplay/',recowishdisplay),
    path('recoadmindisplay/',recoadmindisplay),
    path('recoadmindeletes/<int:id>',recoadmindelete),
    path('recoadminedits/<int:id>',recoadminedit),
    path('customerreview/',customerreview),
    path('indexone/',reviewdisplayview),
    path('aboutuspage/',aboutpage),
    path('contactpage/',contactpage),
    path('termscondition/',termscondition),
    path('reviewdelete/<int:id>',reviewdelete),
    path('reviewedit/<int:id>',reviewedit),
    path('emptycartitems/',emptycartitems),
    path('emptywishlistitems/',emptywishlistitems),
    path('forgot_password/',forgot_password),
    path('changepassword/<int:id>',change_password),
    path('thankyou/',thankyou)



    ]

