# Generated by Django 4.2.4 on 2023-08-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('proid', models.CharField(max_length=20)),
                ('prodes', models.CharField(max_length=550)),
                ('proimage', models.FileField(upload_to='main_app/static')),
                ('proprice', models.IntegerField()),
            ],
        ),
    ]
