# Generated by Django 4.2.4 on 2023-08-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_wishmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('cname', models.CharField(max_length=50)),
                ('cdid', models.CharField(max_length=50)),
                ('cimage', models.FileField(upload_to='')),
                ('cprice', models.IntegerField()),
            ],
        ),
    ]
