# Generated by Django 4.2.4 on 2023-08-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='videomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='main_app/static')),
                ('pdfname', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='main_app/static')),
            ],
        ),
    ]
