# Generated by Django 4.2.4 on 2023-08-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_videomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='prdgallerymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdtfname', models.CharField(max_length=20)),
                ('pdtfimage', models.FileField(upload_to='main_app/static')),
                ('pdtfquan', models.IntegerField()),
                ('pdtffea', models.CharField(max_length=200)),
                ('pdtfdate', models.DateField()),
                ('pdtfnewname', models.CharField(max_length=20)),
                ('pdtfnewimage', models.FileField(upload_to='main_app/static')),
                ('pdtfnewquan', models.IntegerField()),
                ('pdtffeanew', models.CharField(max_length=200)),
                ('pdtfdatenew', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
