# Generated by Django 4.2.4 on 2023-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_prdgallerymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsfeedmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=400)),
                ('image', models.FileField(upload_to='final_app/static')),
                ('rate', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
