# Generated by Django 4.2.4 on 2023-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_newsfeedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeedmodel',
            name='image',
            field=models.FileField(upload_to='main_app/static'),
        ),
    ]
