# Generated by Django 4.2.4 on 2023-08-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_newsfeedmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='newswishmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsurid', models.IntegerField()),
                ('newsid', models.IntegerField()),
                ('wnhead', models.CharField(max_length=100)),
                ('wncon', models.CharField(max_length=400)),
                ('wnimage', models.FileField(upload_to='')),
                ('wnrate', models.IntegerField()),
                ('wndiscount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
