# Generated by Django 4.2.4 on 2023-08-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_newswishmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('select', models.CharField(choices=[('Creditcard', 'Creditcard'), ('Debitcard', 'Debitcard'), ('Paytym', 'Paytym'), ('Googlepay', 'Googlepay')], max_length=50)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
