# Generated by Django 4.2.4 on 2023-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_paymentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendedmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdtreconame', models.CharField(max_length=50)),
                ('pdtrecoimage', models.FileField(upload_to='main_app/static')),
            ],
        ),
    ]
