# Generated by Django 4.2.4 on 2023-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_recommendedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusimage', models.FileField(upload_to='main_app/static')),
                ('cuname', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=500)),
                ('deleplace', models.CharField(max_length=100)),
                ('deldate', models.DateField()),
                ('occation', models.CharField(max_length=60)),
            ],
        ),
    ]
